# 6월 12일 학습 정리

## 클래스
- 클래스와 객체
    ### 기본 정리
    - 객체 지향 프로그래밍: 객체의 개념을 프로그램에 도입
    - 객체: 변수들, 함수들도 구성 -> 메모리에 올라가있는 상태
    - 클래스: 변수들과 함수들이 어떻게 구성되는지의 설계도 -> 변수들을 정의, 함수들을 정의
    - class 클래스 이름:
        - 변수들과 함수들을 정의
    - 클래스의 정의 -> 새로운 사용자 정의 타입을 만든 것
    - 객체 생성 방식 -> 변수 = 클래스 이름()
    - 객체의 활용: 변수.객체가 가지는 변수, 변수.객체가 가지는 함수(), 메서드(객체가 가지는 함수)
    
## 클래스와 객체
- 클래스로 만든 객체의 특징:
    * 개체마다 고유한 성격을 가짐
    * 동일한 클래스로 만든 객체들은 서로 전혀 영향을 주지 않음

- 메서드: 클래스 안에 구현된 함수. 클래스에 포함되어 있다는 점만 제외하면 일반 함수와 같다.




## 생성자
- AttrubuteError:
    * 객체의 객체변수가 생성되지 않은 채 객체 변수를 필요로 하는 메서드를 수행하면 에러가 발생한다.
- 객체가 생성될 때 자동으로 호출되는 메서드
- 메서드 명으로 __init__ 사용
- 객체에 초기 값을 설정해야 할 필요가 있을 때 생성자를 구현하는 것이 안전한 방법이다.
- **객체 생성 시 생성자의 매개변수에 해당하는 값을 반드시 전달해야 한다.**

In [2]:
#클래스 정의
class Cookies:
    pass

c1 = Cookies()
c2 = Cookies()

print(id(c1), type(c1))
print(id(c2), type(c2))

2523793128624 <class '__main__.Cookies'>
2524301168784 <class '__main__.Cookies'>


In [13]:
#사칙 연산을 하는 클래스 정의: 클래스 이름, 변수, 함수
#변수는 두 개, 함수(메서드) 4개
class FourCal:
    #초기화(변수 선언->최초 데이터를 할당) 메서드->생성자, 생성자 함수
    def __init__(self, first, second):
        self.first = first
        self.second = second
    
    #클래스에서 함수를 정의할 때에는 반드시 self 매개변수를 받아야 한다.
    #self -> 객체 자신을 가르키는 변수(객체의 주소)
    def setdata(self, first, second):
        self.first = first
        self.second = second

    #사칙연산 함수
    def add(self):
        return self.first + self.second
    
    def sub(self):
        return self.first - self.second
    
    def mul(self):
        return self.first * self.second
    
    def div(self):
        return self.first / self.second
    


In [15]:
cal_1 = FourCal(1, 2)
#cal_1.setdata(100,200)

type(cal_1)


__main__.FourCal

In [22]:
print(cal_1.first)
print(cal_1.second)

100
200


In [ ]:
cal_1.setdata(20,50)    #데이터 설정

In [24]:
print(cal_1.first, cal_1.second)
print(cal_1.add())
print(cal_1.sub())
print(cal_1.mul())
print(cal_1.div())

20 50
70
-30
1000
0.4


In [29]:
#학생 class 생성 -> 객체 생성
#변수: 학번, 이름, 국어 점수, 영어 점수, 수학 점수
#기능: 전체 데이터 출력하는 메서드 (이름, 학번, 총점, 평균)
#   총점 계산
#   평균 계산
# 시뮬레이션: 테스트 학생 데이터 생성 -> 결과 출력

class Student:

    #데이터 초기화
    def __init__(self, name, sno, k_score, e_score, m_score):
        self.s_name = name
        self.s_no = sno
        self.k_score = k_score
        self.e_score = e_score
        self.m_score = m_score

    #총점 계산
    def sum(self):
        return self.k_score + self.e_score + self.m_score
    
    #평균 계산
    def avg(self):
        return self.sum()/3

    #출력 함수
    def print_result(self):
        print('성적표', '-' * 20)
        print(f'이름: {self.s_name} 학번: {self.s_no}')
        print('국어: ', self.k_score)
        print('영어: ', self.e_score)
        print('수학: ', self.m_score)
        print('총점: ', self.sum())
        print('평균: ', self.avg())
    
         

In [36]:
st_1 = Student()    #매개변수 추가해주어야 함

TypeError: Student.__init__() missing 5 required positional arguments: 'name', 'sno', 'k_score', 'e_score', and 'm_score'

In [35]:
print(type(st_1))

<class 'type'>


In [38]:
st_2 = Student('손흥민', 12345, 80, 70, 60,)
st_2.print_result()


성적표 --------------------
이름: 손흥민 학번: 12345
국어:  80
영어:  70
수학:  60
총점:  210
평균:  70.0


In [40]:
Students = [
    Student('영', 12340, 80, 70, 60,),
    Student('일', 12341, 80, 70, 60,),
    Student('이', 12342, 80, 70, 60,),
    Student('삼', 12343, 80, 70, 60,),
    Student('사사', 12344, 80, 70, 60,)
]

for s in Students:
    s.print_result()


성적표 --------------------
이름: 영 학번: 12340
국어:  80
영어:  70
수학:  60
총점:  210
평균:  70.0
성적표 --------------------
이름: 일 학번: 12341
국어:  80
영어:  70
수학:  60
총점:  210
평균:  70.0
성적표 --------------------
이름: 이 학번: 12342
국어:  80
영어:  70
수학:  60
총점:  210
평균:  70.0
성적표 --------------------
이름: 삼 학번: 12343
국어:  80
영어:  70
수학:  60
총점:  210
평균:  70.0
성적표 --------------------
이름: 사사 학번: 12344
국어:  80
영어:  70
수학:  60
총점:  210
평균:  70.0


## 클래스의 상속
- 물려받다는 뜻으로, 어떤 클래스를 만들 때 다른 클래스의 기능을 물려받을 수 있게 만드는 것
    - class 클래스_이름(상속할_클래스_이름)

- 메서드 오버라이딩: 부모 클래스(상속한 클래스)에 있는 메서드를 동일한 이름으로 다시 만드는 것

In [18]:
#FourCal 클래스를 상속하는 MoreFourCal 클래스
class MoreFourCal(FourCal):
    def pow(self):
        if self.second == 0:
            return 0
        else:
            return self.first / self.second
        

In [ ]:
#FourCal 클래스를 상속하여 FourCal 클래스의 모든 기능을 사용할 수 있어야 함
mcal_1 = MoreFourCal()


TypeError: FourCal.__init__() missing 2 required positional arguments: 'first' and 'second'

In [20]:
mcal_1 = MoreFourCal(100,8)


In [21]:
print(mcal_1.add())
print(mcal_1.sub())
print(mcal_1.mul())
print(mcal_1.div())


108
92
800
12.5


## 모듈
- 함수나 변수 또는 클래스를 모아 놓은 파일
- 다른 파이썬 프로그램에서 불러와 사용할 수 있도록 만든 파이썬 파일
    * .py라는 파일을 모두 모듈이라고 부르고 쓴다.
    * 파일 안에 코드들을 작성하고 **파일 단위**로 관리한다. -> 모듈 
    * 함수, 클래스, 변수들(공통의 목적을 위해 만들어진)을 하나의 파일에 모아두고 파일 단위로 저장하는 것. 
    * 모듈들을 모아서 코드를 조립/실행시킬 수 있다. **모듈의 이름이 모듈의 기능**
- pycache: 모듈을 빠르게 엑세스해서 사용할 수 있도록 cpython 파일을 생성한다.

### 모듈 불러오기
- mod1이라는 모듈을 불러올 때, **import mod1** 사용.
- mod1의 add 함수를 이용할 때, mod1.add(1,2) 형식으로 사용.(모듈이름 뒤에 도트 연산자를 붙이고 함수 이름 입력)
    * 모듈 이름 없이 함수 이름만 사용하고 싶은 경우 -> 함수만 import -> from mode1 import add, sub (*은 모든 함수를 불러온다는 뜻)

* **모듈 import할 때 오류가 나는 이유** 
    * 디렉터리가 다를 때 발생하는 오류. -> 절대경로를 사용하여 해결할 수 있다.
### if __name__=="__main__": 의 의미
- 이렇게 수정하지 않은 모듈을 import할 때 모듈 파일이 실행되어 결과 값을 출력하는 문제가 발생한다. 이를 방지하기 위해 사용한다.(main이 자신의 파일일 경우에만 실행.)


## 표준 라이브러리
- 파이썬을 설치할 때 자동으로 컴퓨터에 설치되는 라이브러리로, 유용한 프로그램을 모아 놓은 것이다.
- 라이브러리는 모듈들의 묶음이라 할 수 있다.

### 대표적인 표준 라이브러리
- datetime.date: 연, 월, 일로 날짜를 표현할 때 사용하는 함수
- time
    * time.time()
    * time.localtime()
    * time.asctime()
    * time.ctime()
    * time.strftime()
    * time.sleep()
- random
    * 난수를 발생시키는 모듈
    * random.random()
    * random.sample()
    * random.choice()
    * random.randint()
- os
    * 환경 변수나 디렉터리, 파일 등의 os 자원을 제어할 수 있게 해주는 모듈
    * os.envion
    * os.chdir()
    * os.getcwd()
    * os.system()
    * os.popen()
    * os.mkdir() / os.rmdir()
    * os.remove()
    * os.rename()
- json
    * json 데이터를 쉽게 처리하고자 사용하는 모듈
    * json.load(f)
    * json.dump(data, f)
    * json.dumps(d)
    * json.loads(json_data)
    * **키 부분은 문자열, 큰 따옴표 사용. value 부분도 큰 따옴표 사용, true/false 소문자 사용. 데이터 구조를 만들어 네트워크에서 데이터를 보내고 받는 용도로 사용한다.**


In [1]:
#표준 모듈 사용해보기
#datetime 
import datetime
day1 = datetime.date(2025, 6, 12)
print(day1)

2025-06-12


In [2]:
day2 = datetime.date(2025,1,1)
print(day1-day2)

162 days, 0:00:00


In [4]:
#time
import time
time.time()

1749733700.552882

In [5]:
time.localtime()

time.struct_time(tm_year=2025, tm_mon=6, tm_mday=12, tm_hour=22, tm_min=8, tm_sec=45, tm_wday=3, tm_yday=163, tm_isdst=0)

In [6]:
time.ctime()

'Thu Jun 12 22:09:12 2025'

In [7]:
#random
import random

random.random() # 1보다 작다.

0.42933670977781124

In [32]:
random.randint(60,100)  #60부터 100까지 중 한 숫자.

83

In [33]:
list_score = []
for s in range(0,10):
    list_score.append(random.randint(60,100))

print(list_score)

[66, 100, 61, 80, 74, 75, 69, 99, 79, 86]


In [34]:
random.choice([1,2,3,4,5,6,7,8])    #하나의 숫자 선택

7

In [36]:
random.sample([1,2,3,4,5,6,7,8,9], 5)   #랜덤 5개 선택

[2, 7, 8, 6, 5]

In [37]:
#os
import os
os.environ

environ{'ALLUSERSPROFILE': 'C:\\ProgramData',
        'APPDATA': 'C:\\Users\\choyk\\AppData\\Roaming',
        'APPLICATIONINSIGHTS_CONFIGURATION_CONTENT': '{}',
        'APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL': '1',
        'APPLICATION_INSIGHTS_NO_STATSBEAT': 'true',
        'CHROME_CRASHPAD_PIPE_NAME': '\\\\.\\pipe\\crashpad_17296_KNYYKCHQZCGMNLXY',
        'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
        'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
        'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
        'COMPUTERNAME': 'CHO',
        'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe',
        'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData',
        'EFC_9308_1262719628': '1',
        'EFC_9308_1592913036': '1',
        'EFC_9308_2283032206': '1',
        'EFC_9308_2775293581': '1',
        'EFC_9308_3789132940': '1',
        'ELECTRON_RUN_AS_NODE': '1',
        'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer',
   

In [39]:
os.getcwd() #현재 디렉터리 반환 

'c:\\Users\\choyk\\Documents\\GitHub\\Sk-Study\\study_June'

In [43]:
#os.chdir('C:\\project\\py_project') #디렉터리 변경 


In [ ]:
# os.mkdir('test')    #test 디렉터리 생성
# os.rmdir('test')    #test 디렉터리 삭제

In [42]:
#json
import json
with open('data.json', 'r', encoding='utf8') as f:
    data = json.load(f) #f: 파일

print(data, type(data))     #딕셔너리 형태 


{'name': '김씨', 'age': 30, 'number': 7} <class 'dict'>


In [45]:
json_str_data = json.dumps(data)
print(json_str_data,type(json_str_data))    #딕셔너리를 다시 데이터 str형태로 변환.

{"name": "\uae40\uc528", "age": 30, "number": 7} <class 'str'>


## 외부 모듈
- 내장 함수, 표준 모드, 외부 모듈 => 남이 만든 것. 필요 시 설치하면 된다.
- 설치 : pip 설치.
    - pip install Module_Name


## 넘파이 Numpy
- 넘파이 라이브러리
    - pip install Numpy

- 넘파이는 수치 계산에 특화된 라이브러리

- 다차원 배열(리스트) 객체인 ndarray를 중심으로 작동
    - 고성능 다차원 배열 객체를 제공하며, 요소의 데이터 타입을 통일

- 다양한 함수 지원: 배열 연산, 선형 대수, 푸리에 변환, 난수 생성 등 **다양한 수학적 기능을 제공**

### 주요 기능과 문법
- 배열 생성: np.array(), np.zeros(), np.ones(), np,arange(), np.linspace() 등

- 배열 연산: +,-,*,/와 같은 기본 연산과 np.dot()(행렬 곱), np.sum()(리스트의 합), np.mean() 등 통계 계산

- 배열 변형: reshape(), flatten(), transpose()
    - 1차원 리스트를 2차원으로, 2차원을 1차원으로 변환하는 등의 변환이 가능하다.

- **브로드캐스팅**: 배열 크기가 달라도 호환 가능하면 연산 수행

### 기본 문법
- 넘파이는 배열(ndarray)를 중심으로 이루어져 있다.
    - 기본 배열 생성: np.array([리스트의 요소])
        - 파이썬 리스트를 배열로 변환
    
    - 넘파이 배열 생성: 특별한 배열 생성 - 배열 생성에 유용한 함수를 제공
        * 0으로 채워진 배열: zeros = np.zeros((2,3))    #2,3은 배열의 행,열
        * 1로 채워진 배열: ones = np.ones((3,2))
        * 일련번호 생성되는 배열: np.arange((1부터,10미만만,2간격으로))
        * 지정된 범위 안에서 동일한 간격으로 숫자를 생성: linspace = np.linspace(0부터,10이하,4개의 데이터로)
        * 배열의 속성 확인:
            * arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
            * print(type(arr1))
            * print(arr1.shape)   #배열을 파악. 배열의 크기(행,열) -> (3,3)
            * print(arr1.ndim)    #배열의 차원(깊이) 출력.
            * print(arr1.size)    #배열의 요소의 개수
            * print(arr1.dtype)   #배열의 요소의 데이터 타입
    

        
        

    

In [ ]:
#numpy 사용 선언
import numpy as np


In [2]:
arr = np.array([1,2,3,4,5])

In [5]:
print(arr, type(arr))   #arr은 넘파이 ndarray 타입으로 정의

[1 2 3 4 5] <class 'numpy.ndarray'>


In [ ]:
# 각 요소에 연산 실행
# numpy.ndarray에 + 연산 기호에 수치가 나오면 각각의 요소에 연산을 실행하도록 설계되어있다.
arr + 10

array([11, 12, 13, 14, 15])

In [7]:
#배열의 생성
# 0으로 채워지는 배열 생성
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# 1로 채우는 배열
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
#일련번호 생성되는 배열
#0과 10 사이의 숫자를 2씩 간격으로 생성
seq_1 = np.arange(0, 10, 2)
print(seq_1)

[0 2 4 6 8]


In [13]:
# 지정된 범위 안에서 동일한 간격으로 숫자를 생성
# 0~1 5개로 구분
linspace = np.linspace(1, 11, 5)
print(linspace)

[ 1.   3.5  6.   8.5 11. ]


In [23]:
#배열의 속성 확인
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(type(arr1))
print(arr1.shape)   #배열을 파악. 배열의 크기(행,열) -> (3,3)
print(arr1.ndim)    #배열의 차원(깊이) 출력.
print(arr1.size)    #배열의 요소의 개수
print(arr1.dtype)   #배열의 요소의 데이터 타입

<class 'numpy.ndarray'>
(3, 3)
2
9
int64
