# 6월 13일 학습 정리
- 넘파이(Numpy)
    - 인공지능 모델 개발에 필요한 기능
    - 동영상, 이미지, 바이너리 등 연산에 사용되는 라이브러리.


## 넘파이

### 넘파이 배열의 인덱싱과 슬라이싱
- 인덱싱: 파이썬 리스트처럼 배열의 특정 위치에 접근
- 2D 배열에서는 행과 열을 지정하여 접근
    * [행 index], [열 index] 
    * arr = np.array([[1,2,3],[4,5,6]])
    * arr[0][1]: #0행 1열


In [4]:
# 인덱싱: list와 사용 방법이 같다.
import numpy as np 

arr = np.array([10,20,30,40])

In [5]:
arr

array([10, 20, 30, 40])

In [9]:
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
#print(arr[4]) 인덱싱에러
print(arr[-1])  # 마지막 요소

10
20
30
40
40


In [ ]:
#2차원 형식의 리스트
arr0 = np.array([[1,2,3,],[4,5,6]]) # arr0 [행 index], [열 index] 
arr0

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(arr0[1][2])   # 1행 2열 출력 
print(arr0[1])      # 1행 출력 

6
[4 5 6]


### 슬라이싱
- 배열의 일부분을 추출
- 2D 배열에서도 슬라이싱
- 인덱싱과 비슷하게 [행 인덱스, 열 인덱스] 방식으로 접근한다.
    * arr[시작 행 인덱스 : 종료 행 인덱스, 시작 열 인덱스 : 종료 열 인덱스]

In [22]:
# 슬라이싱
arr1 = np.array([10,20,30,40,50])
print(arr1[:])
print(arr1[1:4]) #index 1번부터 출력. 4번을 만나면 탈출 

[10 20 30 40 50]
[20 30 40]


In [27]:
# 3 x 3 배열
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
# 0행부터 2행까지 1열부터 끝열까지 출력
print(arr[:2,1:])

[[2 3]
 [5 6]]


In [29]:
print(arr[1:, :2])

[[4 5]
 [7 8]]


In [ ]:
# 배열의 연산
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# +, * , **, 

print(arr1+arr2)
print(arr1*arr2)    #배열 요소들의 곱
print(arr1**arr2)   #arr1 요소들에 arr2 요소들 제곱 연산
print(arr1 + 10)    

[5 7 9]
[ 4 10 18]
[  1  32 729]
[11 12 13]


In [34]:
# 2차원 배열의 연산
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3*arr3)

[[ 1  4  9]
 [16 25 36]]


### 형변환/구조 변환
- 1차원을 다차원으로, 다차원을 1차원으로 등 요소를 필터링 하는 것.
- 구조 변경: 1->2, 2->1
- reshape:
    * 배열.reshape(행, 열) -> 일차원을 다차원으로 변환 
- flatten() -> 다차원을 일차원으로 변환 

* 특정 배열을 가져와 일차원으로 변환한 후 필터링을 통해 특정 데이터를 처리 후 다시 다차원으로 변환하는 등의 작업이 가능하다.


In [ ]:
#형변환. 일차원을 다차원으로 변환 
arr = np.array([1,2,3,4,5,6])   # [1,2,3], [4,5,6]으로 형변환 할 예정

reshape = arr.reshape(2,3)  # reshape(행, 열)
print(reshape)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 다차원을 일차원으로 변환 
flat_arr = arr.flatten()
print(flat_arr)

[1 2 3 4 5 6]


In [ ]:
#필터링
arr = np.array([1,2,3,4,5,6])
filter_arr = arr[arr>3] #조건식을 사용해 필터링 할 수 있다.
print(filter_arr)

[4 5 6]


### 랜덤 데이터 생성
- 난수 생성: AI 모델의 초기 가중치나 무작위 데이터 생성에 사용
    - np.random.rand(3) : 0<= n <1 사이의 랜덤 값 3개 선택
    - np.random.randint(1, 10, size=(2,3)): 1~10(10미만) 사이의 정수 난수 생성. 사이즈는 2행 3열

In [39]:
#넘파이를 이용한 난수 생성 => 배열
ran_val = np.random.rand(5)
print(ran_val)

[0.89027792 0.03766168 0.67900921 0.83993173 0.130553  ]


In [73]:
ran_val2 = np.random.randint(1, 10, size=(2,3))
print(ran_val2)

[[1 8 5]
 [4 2 7]]
